# Start from official lightweight Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy only requirements.txt first for layer caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app code
COPY flaskapi.py .
COPY ../mlruns ../mlruns  # assuming your model is saved in ../mlruns

# Expose the port your app runs on
EXPOSE 5000

# Start the Flask app
CMD ["python", "flaskapi.py"]
